[BallisticMelee]
; Enables melee/unarmed weapons to utilize ammo.
bEnabled = 1

[BetterCounter]
; Enables customization of ammo counter display values.
bEnabled = 0
; Hide ammo counter.
bHideCounter = 0
; Add loaded rounds to reserve count.
bAddClipToTotal = 0
; Hide reserve count.
bHideReserve = 0
; Show clip size of equipped weapon.
bShowClipSize = 0
; Replace reserve count with number of magazines left.
bReplaceTotalWithMagCount = 0
; Seperator string between clip info and reserve.
sReserveSeperator = "/"
; Seperator string between clip count and clip size.
sClipSeperator = "|"

[BottomlessClip]
; Enables bottomless clips when weapon form clip size is set to zero.
bEnabled = 1

[GuidedProjectiles]
; Enables line of sight guided projectiles using pursuit guidance law.
; The entries in each config sub section are combined with logical AND.
; Allowed entries {sWeapon, sWeaponMod, sAmmo, sProjectile, fRayCastRange}. 
; Entries use FormID or EditorID, but using EditorID will likely require JohnnyGuitar to be installed.
; Projectile must not be hitscan.
;
; Example enabling guided projectile for Missile Launcher with guidance system mod using any ammo/projectile:
;
; [GuidedProjectile.MissileLauncher]
; sWeapon=WeapMissileLauncher 
; sWeaponMod=ModNVMissileLauncherGuidanceSys

bEnabled = 0
