[BallisticMelee]
; Enables melee/unarmed weapons to utilize ammo.
bEnabled = 1

[BetterCounter]
; Enables customization of ammo counter display values.
bEnabled = 0
; Hide ammo counter.
bHideCounter = 0
; Add loaded rounds to reserve count.
bAddClipToTotal = 0
; Hide reserve count.
bHideReserve = 0
; Show clip size of equipped weapon.
bShowClipSize = 0
; Replace reserve count with number of magazines left.
bReplaceTotalWithMagCount = 0
; Seperator string between clip info and reserve.
sReserveSeperator = "/"
; Seperator string between clip count and clip size.
sClipSeperator = "|"

[BottomlessClip]
; Enables bottomless clips when weapon form clip size is set to zero.
bEnabled = 1

